addInObservation final tidy
oxford-pharmacoepi/CohortProfiles pull request #45
Opened 2023-02-16 13:57 UTC by KimLopezGuell

2023-02-22 09:31 UTC, KimLopezGuell commented
both addInObservation updated and addFollowUp added

2023-02-24 09:26 UTC, catalamarti requested changes

2023-02-24 09:26 UTC, catalamarti commented on R/addFollowUp.R
> +    )
+1

2023-02-24 09:26 UTC, catalamarti commented on R/addFollowUp.R
> +  name = rlang::enquo(name)
add warning if name is already a column in x

2023-02-27 19:36 UTC, catalamarti approved these changes

2023-02-27 19:36 UTC, merged