Updated function inObservation : R code, documentation and tests added.
oxford-pharmacoepi/CohortProfiles pull request #7
Opened 2023-01-20 17:56 UTC by KimLopezGuell

2023-01-24 14:30 UTC, catalamarti requested changes

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  checkmate::assertTRUE(xCheck, add = errorMessage)
I think this line is not necessary

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  checkmate::assertTRUE(cdmCheck,
same here

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  cdmObsPeriodCheck <- inherits(cdm$observation_period, "tbl_dbi")
you have to check first if observation period is contained in cdm

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  checkmate::assertCharacter(observationAt,
how to handle if length is not 1?

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  column2Check <- "subject_id" %in% colnames(x)
It would be nice that you can also work with a table with person_id instead of subject_id

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  column3Check <- "person_id" %in% colnames(cdm$observation_period)
I would not tdo this check as it is out of scope of the function, but happy if you want to include it, same for the subsequent ones.

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  checkmate::assert_logical(compute,
len = 1

2023-01-24 14:30 UTC, catalamarti commented on R/inObservation.R
> +  checkmate::assertCharacter(name,
len = 1?

2023-01-26 14:01 UTC, KimLopezGuell commented
Alternative pull request added that does not have problems in dependencies. Therefore this branch can be deleted.

2023-01-26 14:01 UTC, closed without merging